In [2]:
import pandas as pd    #import pandas library
import numpy as np     #import numpy library

In [4]:
data=pd.read_excel("C:/Users/ping6/Downloads/Telco-Customer-Churn.xlsx")   #read data from excel file

C:\ProgramData\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [5]:
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [61]:
data.head(5)  #read the first 5 rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# S-1

# Customers own their connection based on gender and citizenship

In [19]:
d1=data[data["Churn"]=="No"];d1  #take data of customers own their connection.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.90,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7037,2569-WGERO,Female,0,No,No,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,No
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [13]:
d1["gender"].value_counts()  #returs number of male and female customers.

Male      2625
Female    2549
Name: gender, dtype: int64

In [15]:
d1["SeniorCitizen"].value_counts() #returns number of customer based on citizenship

0    4508
1     666
Name: SeniorCitizen, dtype: int64

# S-2

# Customers left  their service base on gender and citizenship

In [20]:
d2=data[data["Churn"]=="Yes"];d2  # take data of customers left their connection.

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7021,1699-HPSBG,Male,0,No,No,12,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Electronic check,59.80,727.80,Yes
7026,8775-CEBBJ,Female,0,No,No,9,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
7032,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
7034,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [22]:
d2["gender"].value_counts()   #return number customer left the service based on gender

Female    939
Male      930
Name: gender, dtype: int64

In [23]:
d2["SeniorCitizen"].value_counts()  #return number of customer left their service based on cityzenship

0    1393
1     476
Name: SeniorCitizen, dtype: int64

# S-3

# 3.Preference of  payment method based on churn and contract

In [26]:
data["PaymentMethod"].unique()   # finding unique value in the column name PaymentMethod

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [27]:
data["Contract"].unique()  # finding unique value in the column name Contract

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [28]:
# Preference of payment method based on customers own their service in percentage

d1["PaymentMethod"].value_counts(normalize=True)*100

Mailed check                 25.202938
Electronic check             25.009664
Credit card (automatic)      24.932354
Bank transfer (automatic)    24.855044
Name: PaymentMethod, dtype: float64

In [62]:
# Preference of payment method based on customers left their service in percentage

d2["PaymentMethod"].value_counts(normalize=True)*100

Electronic check             57.303371
Mailed check                 16.479401
Bank transfer (automatic)    13.804173
Credit card (automatic)      12.413055
Name: PaymentMethod, dtype: float64

In [30]:
d3 = data[data['Contract'] == 'Month-to-month']   #Defining a dataframe of column "Contract" having value "Month-to-Month"
d4 = data[data['Contract'] == 'One year']         #Defining a dataframe of column "Contract" having value "One year"
d5 = data[data['Contract'] == 'Two year']         #Defining a dataframe of column "Contract" having value "Two year"

In [33]:
d3["PaymentMethod"].value_counts(normalize=True)*100  # Preference of payment method based on customers having contract "Month-to-Month"in percentage

Electronic check             47.741935
Mailed check                 23.045161
Bank transfer (automatic)    15.200000
Credit card (automatic)      14.012903
Name: PaymentMethod, dtype: float64

In [34]:
d4["PaymentMethod"].value_counts(normalize=True)*100  # Preference of payment method based on customers having contract "One year"in percentage

Credit card (automatic)      27.019688
Bank transfer (automatic)    26.544467
Electronic check             23.557366
Mailed check                 22.878479
Name: PaymentMethod, dtype: float64

In [35]:
d5["PaymentMethod"].value_counts(normalize=True)*100   #Preference of payment method based on customers having contract "Two year"in percentage

Credit card (automatic)      34.277286
Bank transfer (automatic)    33.274336
Mailed check                 22.536873
Electronic check              9.911504
Name: PaymentMethod, dtype: float64

# S-4

# 4.Internet service preference by gender based on churn status.

In [36]:
data["InternetService"].unique()  #finding unique values of the column InternetService

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [37]:
# Internet service preference by Male customers own their service in percentage
d6 = d1[data["gender"] == "Male"]
d6['InternetService'].value_counts(normalize = True)*100

<ipython-input-37-3c71c245b0a6>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d6 = d1[data["gender"] == "Male"]

DSL            37.828571
Fiber optic    34.666667
No             27.504762
Name: InternetService, dtype: float64

In [63]:
# Internet service preference by Male customers left their service in percentage
d7 = d2[data["gender"] == "Male"]
d7['InternetService'].value_counts(normalize = True)*100

<ipython-input-63-17c249632518>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d7 = d2[data["gender"] == "Male"]

Fiber optic    68.064516
DSL            25.806452
No              6.129032
Name: InternetService, dtype: float64

In [64]:
# Internet service preference by Female customers own their service in percentage

d8= d1[data["gender"] == "Female"]
d8['InternetService'].value_counts(normalize = True)*100

<ipython-input-64-40fc362a416c>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d8= d1[data["gender"] == "Female"]

DSL            38.014908
Fiber optic    34.876422
No             27.108670
Name: InternetService, dtype: float64

In [43]:
# Internet service preference by Female customers left their service in percentage

d9 = d2[data["gender"] == "Female"]
d9['InternetService'].value_counts(normalize = True)*100

<ipython-input-43-94ffb3d8504d>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  d9 = d2[data["gender"] == "Female"]

Fiber optic    70.713525
DSL            23.322684
No              5.963791
Name: InternetService, dtype: float64

# S-5

# 5. Explain the descriptive statistics of “TotalCharges” based on Gender,Contract, and  Payment Method

In [46]:
data.columns #column names

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [48]:
#the descriptive statistics of “TotalCharges” based on Male Customers
x1=data[data["gender"]=="Male"]
x1["TotalCharges"].describe()

count    3555.000000
mean     2291.680667
std      2273.095299
min        18.800000
25%       399.275000
50%      1406.000000
75%      3778.100000
max      8684.800000
Name: TotalCharges, dtype: float64

In [49]:
#the descriptive statistics of “TotalCharges” based on Female Customers

x2=data[data["gender"]=="Female"]
x2["TotalCharges"].describe()

count    3488.000000
mean     2289.338308
std      2276.695359
min        18.850000
25%       403.300000
50%      1389.050000
75%      3834.062500
max      8672.450000
Name: TotalCharges, dtype: float64

In [54]:
#the descriptive statistics of “TotalCharges” based on Customers having contract of one year
x3=data[data["Contract"]=="One year"]
x3["TotalCharges"].describe()

count    1473.000000
mean     3038.377461
std      2233.477741
min        18.800000
25%       989.450000
50%      2658.400000
75%      4860.350000
max      8684.800000
Name: TotalCharges, dtype: float64

In [57]:
#the descriptive statistics of “TotalCharges” based on Customers having contract of month-to-month
x4=data[data["Contract"]=="Month-to-month"]
x4["TotalCharges"].describe()

count    3875.000000
mean     1369.254581
std      1613.879008
min        18.850000
25%       160.100000
50%       679.550000
75%      2066.500000
max      8061.500000
Name: TotalCharges, dtype: float64

In [58]:
#the descriptive statistics of “TotalCharges” based on Customers having contract of Two year
x5=data[data["Contract"]=="Two year"]
x5["TotalCharges"].describe()

count    1695.000000
mean     3746.752383
std      2582.454154
min        20.350000
25%      1280.125000
50%      3638.250000
75%      6044.300000
max      8672.450000
Name: TotalCharges, dtype: float64

In [59]:
#the descriptive statistics of “TotalCharges” based on Customers having mailed check Payment Method 
x6 = data[data['PaymentMethod'] == 'Mailed check']
x6['TotalCharges'].describe()

count    1612.000000
mean     1083.236973
std      1509.101844
min        18.800000
25%       116.937500
50%       473.675000
75%      1316.000000
max      8476.500000
Name: TotalCharges, dtype: float64

In [60]:
#the descriptive statistics of “TotalCharges” based on Customers having Credit card(automatic) Payment Method
x7 = data[data['PaymentMethod'] == 'Credit card (automatic)']
x7['TotalCharges'].describe()

count    1522.000000
mean     3074.920894
std      2410.536742
min        19.300000
25%       989.400000
50%      2454.175000
75%      5016.550000
max      8670.100000
Name: TotalCharges, dtype: float64

In [72]:
#the descriptive statistics of “TotalCharges” based on Customers having Electronic check Payment Method
x8 = data[data['PaymentMethod'] == 'Electronic check']
x8['TotalCharges'].describe()

count    2365.000000
mean     2090.868182
std      2155.435320
min        18.850000
25%       308.050000
50%      1253.900000
75%      3340.550000
max      8564.750000
Name: TotalCharges, dtype: float64

In [73]:
#the descriptive statistics of “TotalCharges” based on Customers having Bank transfer Payment Method
x9 = data[data['PaymentMethod'] == 'Bank transfer (automatic)']
x9['TotalCharges'].describe()

count    1544.000000
mean     3083.566023
std      2360.362773
min        19.250000
25%      1052.387500
50%      2479.500000
75%      4948.337500
max      8684.800000
Name: TotalCharges, dtype: float64